/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DateTimeStandardizedParseResponse', function() {
    it('should create an instance of DateTimeStandardizedParseResponse', function() {
      // uncomment below and update the code to test DateTimeStandardizedParseResponse
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be.a(CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse);
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

    it('should have the property parsedDateResult (base name: "ParsedDateResult")', function() {
      // uncomment below and update the code to test the property parsedDateResult
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "Year")', function() {
      // uncomment below and update the code to test the property year
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

    it('should have the property month (base name: "Month")', function() {
      // uncomment below and update the code to test the property month
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

    it('should have the property day (base name: "Day")', function() {
      // uncomment below and update the code to test the property day
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

    it('should have the property hour (base name: "Hour")', function() {
      // uncomment below and update the code to test the property hour
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

    it('should have the property minute (base name: "Minute")', function() {
      // uncomment below and update the code to test the property minute
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

    it('should have the property second (base name: "Second")', function() {
      // uncomment below and update the code to test the property second
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

    it('should have the property dayOfWeek (base name: "DayOfWeek")', function() {
      // uncomment below and update the code to test the property dayOfWeek
      //var instane = new CloudmersiveValidateApiClient.DateTimeStandardizedParseResponse();
      //expect(instance).to.be();
    });

  });

}));
