/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LeadEnrichmentResponse', function() {
    it('should create an instance of LeadEnrichmentResponse', function() {
      // uncomment below and update the code to test LeadEnrichmentResponse
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be.a(CloudmersiveValidateApiClient.LeadEnrichmentResponse);
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property leadType (base name: "LeadType")', function() {
      // uncomment below and update the code to test the property leadType
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property contactBusinessEmail (base name: "ContactBusinessEmail")', function() {
      // uncomment below and update the code to test the property contactBusinessEmail
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property contactFirstName (base name: "ContactFirstName")', function() {
      // uncomment below and update the code to test the property contactFirstName
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property contactLastName (base name: "ContactLastName")', function() {
      // uncomment below and update the code to test the property contactLastName
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property contactGender (base name: "ContactGender")', function() {
      // uncomment below and update the code to test the property contactGender
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "CompanyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyDomainName (base name: "CompanyDomainName")', function() {
      // uncomment below and update the code to test the property companyDomainName
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyHouseNumber (base name: "CompanyHouseNumber")', function() {
      // uncomment below and update the code to test the property companyHouseNumber
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyStreet (base name: "CompanyStreet")', function() {
      // uncomment below and update the code to test the property companyStreet
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyCity (base name: "CompanyCity")', function() {
      // uncomment below and update the code to test the property companyCity
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyStateOrProvince (base name: "CompanyStateOrProvince")', function() {
      // uncomment below and update the code to test the property companyStateOrProvince
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyPostalCode (base name: "CompanyPostalCode")', function() {
      // uncomment below and update the code to test the property companyPostalCode
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyCountry (base name: "CompanyCountry")', function() {
      // uncomment below and update the code to test the property companyCountry
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyCountryCode (base name: "CompanyCountryCode")', function() {
      // uncomment below and update the code to test the property companyCountryCode
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyTelephone (base name: "CompanyTelephone")', function() {
      // uncomment below and update the code to test the property companyTelephone
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property companyVATNumber (base name: "CompanyVATNumber")', function() {
      // uncomment below and update the code to test the property companyVATNumber
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

    it('should have the property employeeCount (base name: "EmployeeCount")', function() {
      // uncomment below and update the code to test the property employeeCount
      //var instane = new CloudmersiveValidateApiClient.LeadEnrichmentResponse();
      //expect(instance).to.be();
    });

  });

}));
