/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.Timezone();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Timezone', function() {
    it('should create an instance of Timezone', function() {
      // uncomment below and update the code to test Timezone
      //var instane = new CloudmersiveValidateApiClient.Timezone();
      //expect(instance).to.be.a(CloudmersiveValidateApiClient.Timezone);
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new CloudmersiveValidateApiClient.Timezone();
      //expect(instance).to.be();
    });

    it('should have the property baseUTCOffset (base name: "BaseUTCOffset")', function() {
      // uncomment below and update the code to test the property baseUTCOffset
      //var instane = new CloudmersiveValidateApiClient.Timezone();
      //expect(instance).to.be();
    });

    it('should have the property now (base name: "Now")', function() {
      // uncomment below and update the code to test the property now
      //var instane = new CloudmersiveValidateApiClient.Timezone();
      //expect(instance).to.be();
    });

  });

}));
