/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.ValidateCountryResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ValidateCountryResponse', function() {
    it('should create an instance of ValidateCountryResponse', function() {
      // uncomment below and update the code to test ValidateCountryResponse
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be.a(CloudmersiveValidateApiClient.ValidateCountryResponse);
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property countryFullName (base name: "CountryFullName")', function() {
      // uncomment below and update the code to test the property countryFullName
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property iSOTwoLetterCode (base name: "ISOTwoLetterCode")', function() {
      // uncomment below and update the code to test the property iSOTwoLetterCode
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property fIPSTwoLetterCode (base name: "FIPSTwoLetterCode")', function() {
      // uncomment below and update the code to test the property fIPSTwoLetterCode
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property threeLetterCode (base name: "ThreeLetterCode")', function() {
      // uncomment below and update the code to test the property threeLetterCode
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property isEuropeanUnionMember (base name: "IsEuropeanUnionMember")', function() {
      // uncomment below and update the code to test the property isEuropeanUnionMember
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property timezones (base name: "Timezones")', function() {
      // uncomment below and update the code to test the property timezones
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property iSOCurrencyCode (base name: "ISOCurrencyCode")', function() {
      // uncomment below and update the code to test the property iSOCurrencyCode
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property currencySymbol (base name: "CurrencySymbol")', function() {
      // uncomment below and update the code to test the property currencySymbol
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property currencyEnglishName (base name: "CurrencyEnglishName")', function() {
      // uncomment below and update the code to test the property currencyEnglishName
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property region (base name: "Region")', function() {
      // uncomment below and update the code to test the property region
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

    it('should have the property subregion (base name: "Subregion")', function() {
      // uncomment below and update the code to test the property subregion
      //var instane = new CloudmersiveValidateApiClient.ValidateCountryResponse();
      //expect(instance).to.be();
    });

  });

}));
