/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ValidateIdentifierRequest', function() {
    it('should create an instance of ValidateIdentifierRequest', function() {
      // uncomment below and update the code to test ValidateIdentifierRequest
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be.a(CloudmersiveValidateApiClient.ValidateIdentifierRequest);
    });

    it('should have the property input (base name: "Input")', function() {
      // uncomment below and update the code to test the property input
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowWhitespace (base name: "AllowWhitespace")', function() {
      // uncomment below and update the code to test the property allowWhitespace
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowHyphens (base name: "AllowHyphens")', function() {
      // uncomment below and update the code to test the property allowHyphens
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowUnderscore (base name: "AllowUnderscore")', function() {
      // uncomment below and update the code to test the property allowUnderscore
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowNumbers (base name: "AllowNumbers")', function() {
      // uncomment below and update the code to test the property allowNumbers
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be();
    });

    it('should have the property allowPeriods (base name: "AllowPeriods")', function() {
      // uncomment below and update the code to test the property allowPeriods
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxLength (base name: "MaxLength")', function() {
      // uncomment below and update the code to test the property maxLength
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be();
    });

    it('should have the property minLength (base name: "MinLength")', function() {
      // uncomment below and update the code to test the property minLength
      //var instane = new CloudmersiveValidateApiClient.ValidateIdentifierRequest();
      //expect(instance).to.be();
    });

  });

}));
