/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.VatLookupResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VatLookupResponse', function() {
    it('should create an instance of VatLookupResponse', function() {
      // uncomment below and update the code to test VatLookupResponse
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be.a(CloudmersiveValidateApiClient.VatLookupResponse);
    });

    it('should have the property countryCode (base name: "CountryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property vatNumber (base name: "VatNumber")', function() {
      // uncomment below and update the code to test the property vatNumber
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property isValid (base name: "IsValid")', function() {
      // uncomment below and update the code to test the property isValid
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessName (base name: "BusinessName")', function() {
      // uncomment below and update the code to test the property businessName
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessAddress (base name: "BusinessAddress")', function() {
      // uncomment below and update the code to test the property businessAddress
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessBuilding (base name: "BusinessBuilding")', function() {
      // uncomment below and update the code to test the property businessBuilding
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessStreetNumber (base name: "BusinessStreetNumber")', function() {
      // uncomment below and update the code to test the property businessStreetNumber
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessStreet (base name: "BusinessStreet")', function() {
      // uncomment below and update the code to test the property businessStreet
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessCity (base name: "BusinessCity")', function() {
      // uncomment below and update the code to test the property businessCity
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessStateOrProvince (base name: "BusinessStateOrProvince")', function() {
      // uncomment below and update the code to test the property businessStateOrProvince
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessPostalCode (base name: "BusinessPostalCode")', function() {
      // uncomment below and update the code to test the property businessPostalCode
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

    it('should have the property businessCountry (base name: "BusinessCountry")', function() {
      // uncomment below and update the code to test the property businessCountry
      //var instane = new CloudmersiveValidateApiClient.VatLookupResponse();
      //expect(instance).to.be();
    });

  });

}));
