/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.DateTimeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DateTimeApi', function() {
    describe('dateTimeGetNowSimple', function() {
      it('should call dateTimeGetNowSimple successfully', function(done) {
        //uncomment below and update the code to test dateTimeGetNowSimple
        //instance.dateTimeGetNowSimple(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dateTimeGetPublicHolidays', function() {
      it('should call dateTimeGetPublicHolidays successfully', function(done) {
        //uncomment below and update the code to test dateTimeGetPublicHolidays
        //instance.dateTimeGetPublicHolidays(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dateTimeParseNaturalLanguageDateTime', function() {
      it('should call dateTimeParseNaturalLanguageDateTime successfully', function(done) {
        //uncomment below and update the code to test dateTimeParseNaturalLanguageDateTime
        //instance.dateTimeParseNaturalLanguageDateTime(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('dateTimeParseStandardDateTime', function() {
      it('should call dateTimeParseStandardDateTime successfully', function(done) {
        //uncomment below and update the code to test dateTimeParseStandardDateTime
        //instance.dateTimeParseStandardDateTime(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
