/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.DomainApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DomainApi', function() {
    describe('domainCheck', function() {
      it('should call domainCheck successfully', function(done) {
        //uncomment below and update the code to test domainCheck
        //instance.domainCheck(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainGetTopLevelDomainFromUrl', function() {
      it('should call domainGetTopLevelDomainFromUrl successfully', function(done) {
        //uncomment below and update the code to test domainGetTopLevelDomainFromUrl
        //instance.domainGetTopLevelDomainFromUrl(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainIsAdminPath', function() {
      it('should call domainIsAdminPath successfully', function(done) {
        //uncomment below and update the code to test domainIsAdminPath
        //instance.domainIsAdminPath(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainPhishingCheck', function() {
      it('should call domainPhishingCheck successfully', function(done) {
        //uncomment below and update the code to test domainPhishingCheck
        //instance.domainPhishingCheck(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainPost', function() {
      it('should call domainPost successfully', function(done) {
        //uncomment below and update the code to test domainPost
        //instance.domainPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainQualityScore', function() {
      it('should call domainQualityScore successfully', function(done) {
        //uncomment below and update the code to test domainQualityScore
        //instance.domainQualityScore(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainSafetyCheck', function() {
      it('should call domainSafetyCheck successfully', function(done) {
        //uncomment below and update the code to test domainSafetyCheck
        //instance.domainSafetyCheck(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainSsrfCheck', function() {
      it('should call domainSsrfCheck successfully', function(done) {
        //uncomment below and update the code to test domainSsrfCheck
        //instance.domainSsrfCheck(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainSsrfCheckBatch', function() {
      it('should call domainSsrfCheckBatch successfully', function(done) {
        //uncomment below and update the code to test domainSsrfCheckBatch
        //instance.domainSsrfCheckBatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainUrlFull', function() {
      it('should call domainUrlFull successfully', function(done) {
        //uncomment below and update the code to test domainUrlFull
        //instance.domainUrlFull(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainUrlHtmlSsrfCheck', function() {
      it('should call domainUrlHtmlSsrfCheck successfully', function(done) {
        //uncomment below and update the code to test domainUrlHtmlSsrfCheck
        //instance.domainUrlHtmlSsrfCheck(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('domainUrlSyntaxOnly', function() {
      it('should call domainUrlSyntaxOnly successfully', function(done) {
        //uncomment below and update the code to test domainUrlSyntaxOnly
        //instance.domainUrlSyntaxOnly(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
