/**
 * validateapi
 * The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveValidateApiClient);
  }
}(this, function(expect, CloudmersiveValidateApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveValidateApiClient.TextInputApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TextInputApi', function() {
    describe('textInputCheckHtmlSsrf', function() {
      it('should call textInputCheckHtmlSsrf successfully', function(done) {
        //uncomment below and update the code to test textInputCheckHtmlSsrf
        //instance.textInputCheckHtmlSsrf(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('textInputCheckSqlInjection', function() {
      it('should call textInputCheckSqlInjection successfully', function(done) {
        //uncomment below and update the code to test textInputCheckSqlInjection
        //instance.textInputCheckSqlInjection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('textInputCheckSqlInjectionBatch', function() {
      it('should call textInputCheckSqlInjectionBatch successfully', function(done) {
        //uncomment below and update the code to test textInputCheckSqlInjectionBatch
        //instance.textInputCheckSqlInjectionBatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('textInputCheckXss', function() {
      it('should call textInputCheckXss successfully', function(done) {
        //uncomment below and update the code to test textInputCheckXss
        //instance.textInputCheckXss(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('textInputCheckXssBatch', function() {
      it('should call textInputCheckXssBatch successfully', function(done) {
        //uncomment below and update the code to test textInputCheckXssBatch
        //instance.textInputCheckXssBatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('textInputCheckXxe', function() {
      it('should call textInputCheckXxe successfully', function(done) {
        //uncomment below and update the code to test textInputCheckXxe
        //instance.textInputCheckXxe(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('textInputCheckXxeBatch', function() {
      it('should call textInputCheckXxeBatch successfully', function(done) {
        //uncomment below and update the code to test textInputCheckXxeBatch
        //instance.textInputCheckXxeBatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('textInputProtectXss', function() {
      it('should call textInputProtectXss successfully', function(done) {
        //uncomment below and update the code to test textInputProtectXss
        //instance.textInputProtectXss(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
